### PR TITLE
[node_editor] fix: add edge create, remove

### LINKED ISSUE #168: [node editor] Repair edge connections

### PR DESCRIPTION
**Pull request by robproject**
### Description
Add edge creation and removal handling to NodeEditor.vue

### Testing
Observe dragging a connection from one node to another creates an edge. 
Observe right-clicking the edge removes it.

### CODE REVIEW

**Review by agritheory — CHANGES_REQUESTED** [review]
@robproject A couple of small things here to make the UX on this a little shinier:

- [x] Handle the ESC as "discard changes / same as clicking outside
- [x] Set default label width to 40ch when editing
- [x] Update Builder example with some edges

- [x] I think this text is probably unintended:
image

**Comment by robproject** [comment]
>     * [x]  Handle the ESC as "discard changes / same as clicking outside
Looks like it already does this?

File: node_editor/src/components/StateEditor.vue [hunk 1]
```diff
@@ -40,31 +40,26 @@ const elements = computed<FlowElements>({
...
-								source: key,
-								label: edgeKey,
-								animated: true,
-							})
-
-							// eslint-disable-next-line @typescript-eslint/no-unsafe-member-access
-							hasInputs[target] = true
-						}
-					}
+					const target = edgeValue.target || edgeValue
```
Comment (robproject) [inline node_editor/src/components/StateEditor.vue:50]: If the proxy array value.on has more than one edge, edgeValue will contain a proxy object where `target` can be accessed. Otherwise, edgeValue will be available directly.

Comment (agritheory) [reply node_editor/src/components/StateEditor.vue:50]: Great comment, let's put it in the code

File: common/changes/@stonecrop/node-editor/168_edge_connections_2024-10-22-01-17.json [hunk 2]
```diff
@@ -0,0 +1,10 @@
+{
+  "changes": [
+    {
+      "packageName": "@stonecrop/node-editor",
+      "comment": "Add handling for edge creation and removal.",
+      "type": "none"
```
Comment (agritheory) [inline common/changes/@stonecrop/node-editor/168_edge_connections_2024-10-22-01-17.json]: Change to "patch" per @Alchez

**Review by agritheory — CHANGES_REQUESTED** [review]

**Review by agritheory — APPROVED** [review]
